% % Create axes
% axes6 = axes('Parent',figure7);
% hold(axes7,'on');
% 
% bar(minValue,populationPerBin(:,3),'histc')
% 

%CREATEFIGURE(VERTICES1, FACES1, CDATA1, X1, Y1, VERTICES2, VERTICES3, VERTICES4)
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  CDATA1:  patch cdata
%  X1:  vector of x data
X1 = binEdges * perc;
% X1(end + 1) = X1(end) + binWidth;
xMin = 0.01;
% ticks(1) = xMin;
% ticks(2:11) = (1:10);
Y1 = populationPerBin(:,3) * perc;
Y2 = populationPerBin(:,2) * perc;
Y3 = populationPerBin(:,4) * perc;
Y4 = populationPerBin(:,5) * perc;
%  Y1:  vector of y data
%  VERTICES2:  patch vertices
%  VERTICES3:  patch vertices
%  VERTICES4:  patch vertices

%  Auto-generated by MATLAB on 19-Feb-2016 00:46:30

% Create figure
figure7 = figure;

%% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure7);
hold(subplot1,'on');

% Create plot
bar(X1,Y1,'histc','Parent',subplot1);

% Create xlabel
xlabel('Work time devoted to reviewing (%)');

% Create ylabel
ylabel('Authors (%)');

% Create title
title('First/last authors');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot1,[xMin xMax]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot1,[0 yMax]);
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'CLim',[1 2]);
% set(subplot1, 'XTick', ticks)

%% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure7);
hold(subplot2,'on');

% Create plot
bar(X1,Y2,'histc','Parent',subplot2);

% Create xlabel
xlabel('Work time devoted to reviewing (%)');

% Create ylabel
ylabel('Authors (%)');

% Create title
title('All authors');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot2,[xMin xMax]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot2,[0 yMax]);
box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'CLim',[1 2]);

%% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure7);
hold(subplot3,'on');

% Create plot
bar(X1,Y3,'histc','Parent',subplot3);

% Create xlabel
xlabel('Work time devoted to reviewing (%)');

% Create ylabel
ylabel('Authors (%)');

% Create title
title('First/second/last');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot3,[xMin xMax]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot3,[0 yMax]);
box(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'CLim',[1 2]);

%% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure7);
hold(subplot4,'on');

% Create plot
bar(X1,Y4,'histc','Parent',subplot4);

% Create xlabel
xlabel('Work time devoted to reviewing (%)');

% Create ylabel
ylabel('Authors (%)');

% Create title
title('First/last 3 past years');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot4,[xMin xMax]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot4,[0 yMax]);
box(subplot4,'on');
% Set the remaining axes properties
set(subplot4,'CLim',[1 2]);


SaveFigureScript