%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 08-Feb-2016 13:11:06

% Create figure
figure6 = figure;

% Create axes
axes6 = axes('Parent',figure6);
hold(axes6,'on');

% Create bar
if reviewingProb(1) < 1
    bar(reviewingProb);
else
    bar(reviewingProb.*0.01);
end

% Create xlabel
xlabel('Reviews per reviewer', 'FontSize', 16);

% Create ylabel
ylabel('Reviewers (%)', 'FontSize', 16);

% Create title
title(name, 'FontSize', 16);

%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes6,[0 20]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes6,[0 0.65]);
box(axes6,'on');
